### ISSUE TITLE
Prepare hhd package for 2.0 and track upstream

### ISSUE THREAD

**Issue by antheas** [Nobara-Project/rpm-sources#23]
Hi,
hhd 2.0 came out last week so it would be good to have it in nobara + fix some issues with the current repository.

The dependency tree for nobara makes it hard right now to install a different version of hhd and the version shipped with nobara does not track the upstream COPR repo. Let's try to fix these issues so that updating is easier in the future.

### Steam Powerbuttond
Right now, `gamescope-session-steam` has as a dependency `steam-powerbuttond`. `steam-powerbuttond` is a completely optional dependency that has an aesthetic purpose (e.g., the wink), and is not optimized to work for all devices (e.g., laptops) so it might cause issues for them. Forcing it to be installed for the session blocks the user for disabling it if it is problematic for their setup. In addition, hhd provides and obsoletes this package, so once the version nobara tracks is installed it cannot be removed.

It should be possible to have the `gamescope-session-steam` package installed without a powerbutton manager.

### Tracking COPR
Nobara forks the spec package for hhd and patches it with 2 enable scripts. This means that it can not track the upstream version semi-automatically. Ideally, nobara would pull from the `hhd-dev/hhd` copr repo as part of its weekly snapshot sync.

As for the patching to add an enable function, perhaps it should be separated to its own package, called e.g., `hhd-enable` that is installed as part of the first time setup in the iso, alongside the upstream `hhd` package.

### Installing additional hhd packages
The new version of hhd comes with 2 optional dependencies that should ideally be added to the nobara repos: hhd-ui, and adjustor.

Those do the following:
  - hhd-ui: Allows hhd to provide a steam overlay overlay to configure the controllers and all other hhd settings. Provided as an AppImage, requires 0 changes to an existing gamescope session.
  - Adjustor: Provides TDP controls for ryzen devices through hhd. For the legion go, this is done with the lenovo space functions. For other devices, acpi_call is used.

Adjustor is already on the hhd-dev [copr](https://copr.fedorainfracloud.org/coprs/hhd-dev/hhd/package/adjustor/). The hhd-ui is not and I do not have a spec file for it yet.

I would love to get a spec file going that just installs the AppImage to `/usr/bin/hhd-ui.AppImage` and adds a desktop file for it.

Here is a video of the overlay:
![overlay](https://github.com/Nobara-Project/rpm-sources/assets/5252246/d0cd66f5-592a-410d-9173-8f95fb480e25)

Tagging @matte-schwartz as he is planning to work on a PR for this.

**Comment by matte-schwartz** [comment]
the current problem:

1. our .spec for `hhd` both `Provides:` and `Obsoletes` `steam-powerbuttond`:  https://github.com/Nobara-Project/rpm-sources/blob/c612e8ed79cb15c209228f89fa70de4a1b66c6a6/baseos/hhd/hhd.spec#L28
hhd has steam-powerbuttond functionality built in now, defaulting to off with an option to enable it.
2. `gamescope-session-steam` + `-plus` both require `steam-powerbuttond` in their .specs, but `hhd` takes priority since it has the `Obsoletes:` tag
3. if you are on a desktop pc, hhd will always get pulled in as a part of gamescope-session.
![image](https://github.com/Nobara-Project/rpm-sources/assets/136293710/b1aa58af-7f3c-49f4-b441-7f17a3972276)
4. this chain results in gamescope-session depending on hhd, so trying to remove hhd individually and use a different input solution (like inputplumber) has to be executed via `rpm -e hhd --nodeps` to avoid removing all of gamescope-session with it.

`inputplumber` does not currently take care of the power button like `hhd` does, so it still needs `steam-powerbuttond` in addition to itself.  inputplumber is a conflict with hhd which is why the fact that `sudo dnf install steam-powerbuttond` pulling `hhd` is difficult for me to figure out. 

my thoughts:

- snapshotting https://copr.fedorainfracloud.org/coprs/hhd-dev/hhd/ probably reduces upkeep if we just grab from antheas' copr  
- might be easiest to pack `hhd`, `hhd-ui`, and `adjustor` like rocm-meta (maybe `hhd-meta`) https://github.com/matte-schwartz/rpm-sources/blob/98bb04bce1d871bf9b1882ecff9764701d372217/baseos/hhd-meta/hhd-meta.spec and then add our method for starting the service with a preset and whatever other tweaks we want to make rather than in the .specs from the components themselves:
- this should help us get out of the current dependency chain we are stuck in.
- could also be a good chance to better utilize the driver manager for handheld device DMIs outside of nobara-sync

what i need from you on this whenever you get a chance @GloriousEggroll :
1. your thoughts on the current packaging situation and how we should address it going forward? i tried juggling .spec macros for longer than i'd like to admit and i'll leave it to someone who actually knows what they're doing to properly sort this out. i can fill out a PR once a direction is decided on.
2. ask @ _antheas , the dev of hhd, in the nobara ally discord thread with any questions on hhd's current scope https://ptb.discord.com/channels/110175050006577152/1134627261413347399

**Comment by GloriousEggroll** [comment]
Updates on WIP:
> We do not use the powerbuttond services. We use the python script packaged with jupiter hw support and it is now gated to only steam deck itself, it is not used for other devices:

https://github.com/Nobara-Project/steamdeck-edition-packages/blob/3f487f3d2c19eb9eaf986d3d047651a820e5e870/gamescope-session-plus/usr/share/gamescope-session-plus/gamescope-session-plus#L255

Neither the gamescope-session-plus nor gamescope-session-steam rely on steam-powerbuttond as a dependency any more in any way.

> I've removed all hard coded references to hhd from gamescope-session-plus. It was not used/referenced in gamescope-session-steam ever, only the base package (plus):

https://github.com/Nobara-Project/steamdeck-edition-packages/commit/3f487f3d2c19eb9eaf986d3d047651a820e5e870

In doing so I've also introduced a new /usr/libexec/ script for generic use with gamescope-session-plus that allows 3rd party services/applications/installers to be able to add commands that can be run in gamescope-session:

https://github.com/Nobara-Project/steamdeck-edition-packages/blob/3f487f3d2c19eb9eaf986d3d047651a820e5e870/gamescope-session-plus/usr/share/gamescope-session-plus/gamescope-session-plus#L271

https://github.com/Nobara-Project/steamdeck-edition-packages/blob/main/gamescope-session-plus/usr/libexec/gs-thirdparty-services

This allows users and/or package maintainers to either add a command to /etc/gamescope-session-plus/run-commands or a .conf file containing the command in /etc/gamescope-session-plus/run-commands.d/ to be executed when gamescope runs.

This should allow hhd or any other 3rd party applications that need to run specifically in gamescope to be able to do so without needing gamescope modifications for the forseeable future.

TODO:
I will cleanup hhd and get it updated to the latest version and remove Nobara's customizations. As for keeping up with copr in the future it'll just be a mattle of keeping our version number here up to date.

**Comment by GloriousEggroll** [comment]
resolved with latest changes
